version: '3.8'

services:
  mongodb:
    # MUDAR DE 'mongo:latest' PARA 'mongo:4.4'
    image: mongo:4.4
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: larissaguimaraesgomes
      MONGO_INITDB_ROOT_PASSWORD: qC2ZSf9RQVYvfktn

volumes:
  mongodb_data:
    driver: local